version: 2
jobs:

  Documentation (3.4.x):
    docker:
     - image: openfl/openfl-tests-unit-3.4:0.0.2
    steps:
     - checkout
     - run:
         name: Setup Development Directory
         command: haxelib dev starling .
     - run:
         name: Clone OpenFL
         command: git clone --recursive https://github.com/openfl/openfl ~/openfl --depth 1
     - run:
         name: Setup OpenFL Development Directory
         command: haxelib dev openfl ~/openfl
     - run:
         name: Clone Lime
         command: git clone --recursive https://github.com/openfl/lime ~/lime --depth 1
     - run:
         name: Setup Lime Development Directory
         command: haxelib dev lime ~/lime
     - run:
         name: Clone Dox
         command: git clone https://github.com/openfl/dox ~/dox --depth 1
     - run:
         name: Set Dox Development Directory
         command: haxelib dev dox ~/dox
     - run:
         name: Generate Documentation
         working_directory: docs
         command: haxe build.hxml


workflows:
  version: 2
  
  Documentation:
    jobs:
     - Documentation (Haxe 3.4.x)